In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("DailyDelhiClimateTrain.csv")

In [3]:
df.head(10)

         date   meantemp   humidity  wind_speed  meanpressure
0  2013-01-01  10.000000  84.500000    0.000000   1015.666667
1  2013-01-02   7.400000  92.000000    2.980000   1017.800000
2  2013-01-03   7.166667  87.000000    4.633333   1018.666667
3  2013-01-04   8.666667  71.333333    1.233333   1017.166667
4  2013-01-05   6.000000  86.833333    3.700000   1016.500000
5  2013-01-06   7.000000  82.800000    1.480000   1018.000000
6  2013-01-07   7.000000  78.600000    6.300000   1020.000000
7  2013-01-08   8.857143  63.714286    7.142857   1018.714286
8  2013-01-09  14.000000  51.250000   12.500000   1017.000000
9  2013-01-10  11.000000  62.000000    7.400000   1015.666667

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1462 entries, 0 to 1461
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          1462 non-null   object
 1   meantemp      1462 non-null   float64
 2   humidity      1462 non-null   float64
 3   wind_speed    1462 non-null   float64
 4   meanpressure  1462 non-null   float64
dtypes: float64(4), object(1)
memory usage: 57.2+ KB

In [5]:
df['date']=pd.to_datetime(df['date'])

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1462 entries, 0 to 1461
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          1462 non-null   datetime64[ns]
 1   meantemp      1462 non-null   float64
 2   humidity      1462 non-null   float64
 3   wind_speed    1462 non-null   float64
 4   meanpressure  1462 non-null   float64
dtypes: datetime64[ns](1), float64(4)
memory usage: 57.2 KB

In [7]:
df.loc[0,'date']

Timestamp('2013-01-01 00:00:00')

In [8]:
df.loc[0,'date'].day_name()

'Tuesday'

In [11]:
df['day']=df['date'].dt.day_name()

In [12]:
df

           date   meantemp    humidity  wind_speed  meanpressure        day
0    2013-01-01  10.000000   84.500000    0.000000   1015.666667    Tuesday
1    2013-01-02   7.400000   92.000000    2.980000   1017.800000  Wednesday
2    2013-01-03   7.166667   87.000000    4.633333   1018.666667   Thursday
3    2013-01-04   8.666667   71.333333    1.233333   1017.166667     Friday
4    2013-01-05   6.000000   86.833333    3.700000   1016.500000   Saturday
...         ...        ...         ...         ...           ...        ...
1457 2016-12-28  17.217391   68.043478    3.547826   1015.565217  Wednesday
1458 2016-12-29  15.238095   87.857143    6.000000   1016.904762   Thursday
1459 2016-12-30  14.095238   89.666667    6.266667   1017.904762     Friday
1460 2016-12-31  15.052632   87.000000    7.325000   1016.100000   Saturday
1461 2017-01-01  10.000000  100.000000    0.000000   1016.000000     Sunday

[1462 rows x 6 columns]

In [15]:
group_day=df.groupby(['day'])

In [18]:
group_mon=group_day.get_group(('Monday',))

In [19]:
group_mon

           date   meantemp   humidity  wind_speed  meanpressure     day
6    2013-01-07   7.000000  78.600000    6.300000   1020.000000  Monday
13   2013-01-14  12.833333  88.166667    0.616667   1015.166667  Monday
20   2013-01-21  11.200000  77.000000    2.220000   1021.000000  Monday
27   2013-01-28  14.833333  56.000000    3.700000   1017.833333  Monday
34   2013-02-04  17.428571  74.285714   11.114286   1014.571429  Monday
...         ...        ...        ...         ...           ...     ...
1427 2016-11-28  22.454545  37.318182    9.185714     12.045455  Monday
1434 2016-12-05  18.636364  56.590909    4.952381   1017.045455  Monday
1441 2016-12-12  19.909091  63.863636    3.281818   1014.181818  Monday
1448 2016-12-19  17.857143  56.095238   10.414286   1017.428571  Monday
1455 2016-12-26  17.142857  74.857143    8.784211   1016.952381  Monday

[208 rows x 6 columns]

In [20]:
group_mon['meantemp'].mean()

np.float64(25.53568885886194)

In [21]:
group_mon['meantemp'].max()

np.float64(38.0)

In [22]:
group_mon['meantemp'].min()

np.float64(7.0)

In [23]:
group_mon['meantemp'].median()

np.float64(27.794642857142858)

In [24]:
group_mon['wind_speed'].min()

np.float64(0.0)

In [25]:
group_mon['wind_speed'].min()

np.float64(0.0)

In [26]:
df['date'].max()-df['date'].min()

Timedelta('1461 days 00:00:00')

In [27]:
df['date'].min()

Timestamp('2013-01-01 00:00:00')

In [28]:
df['date'].max()

Timestamp('2017-01-01 00:00:00')

In [29]:
filt=df['date']>'2015'

In [30]:
df.loc[filt]

           date   meantemp    humidity  wind_speed  meanpressure        day
731  2015-01-02  14.875000   96.625000    3.012500   1017.875000     Friday
732  2015-01-03  15.125000   92.000000    0.925000   1017.375000   Saturday
733  2015-01-04  14.125000   78.750000    9.512500   1019.625000     Sunday
734  2015-01-05  14.000000   69.375000   15.050000   1016.000000     Monday
735  2015-01-06  12.000000   79.875000    4.400000   1015.500000    Tuesday
...         ...        ...         ...         ...           ...        ...
1457 2016-12-28  17.217391   68.043478    3.547826   1015.565217  Wednesday
1458 2016-12-29  15.238095   87.857143    6.000000   1016.904762   Thursday
1459 2016-12-30  14.095238   89.666667    6.266667   1017.904762     Friday
1460 2016-12-31  15.052632   87.000000    7.325000   1016.100000   Saturday
1461 2017-01-01  10.000000  100.000000    0.000000   1016.000000     Sunday

[731 rows x 6 columns]

In [33]:
filt=(df['date']>'2015') & (df['date']<'2016')

In [34]:
df[filt]

           date  meantemp  humidity  wind_speed  meanpressure        day
731  2015-01-02    14.875    96.625      3.0125      1017.875     Friday
732  2015-01-03    15.125    92.000      0.9250      1017.375   Saturday
733  2015-01-04    14.125    78.750      9.5125      1019.625     Sunday
734  2015-01-05    14.000    69.375     15.0500      1016.000     Monday
735  2015-01-06    12.000    79.875      4.4000      1015.500    Tuesday
...         ...       ...       ...         ...           ...        ...
1090 2015-12-27    15.375    63.250      7.8875      1020.625     Sunday
1091 2015-12-28    17.125    58.125     10.8875      1020.875     Monday
1092 2015-12-29    16.375    65.000      7.4125      1018.125    Tuesday
1093 2015-12-30    15.500    71.750      2.1000      1017.500  Wednesday
1094 2015-12-31    15.000    71.375      2.0875      1020.500   Thursday

[364 rows x 6 columns]

In [35]:
df['year'] = df['date'].dt.year

In [38]:
df['month'] = df['date'].dt.month

In [39]:
df['month_name'] = df['date'].dt.month_name()

In [40]:
df

,date,meantemp,humidity,wind_speed,meanpressure,day,year,month,month_name
0,2013-01-01,10.000000,84.500000,0.000000,1015.666667,Tuesday,2013,1,January
1,2013-01-02,7.400000,92.000000,2.980000,1017.800000,Wednesday,2013,1,January
2,2013-01-03,7.166667,87.000000,4.633333,1018.666667,Thursday,2013,1,January
3,2013-01-04,8.666667,71.333333,1.233333,1017.166667,Friday,2013,1,January
4,2013-01-05,6.000000,86.833333,3.700000,1016.500000,Saturday,2013,1,January
...,...,...,...,...,...,...,...,...,...
1457,2016-12-28,17.217391,68.043478,3.547826,1015.565217,Wednesday,2016,12,December
1458,2016-12-29,15.238095,87.857143,6.000000,1016.904762,Thursday,2016,12,December
1459,2016-12-30,14.095238,89.666667,6.266667,1017.904762,Friday,2016,12,December
1460,2016-12-31,15.052632,87.000000,7.325000,1016.100000,Saturday,2016,12,December
1461,2017-01-01,10.000000,100.000000,0.000000,1016.000000,Sunday,2017,1,January

In [42]:
group_year=df.groupby(['year'])

In [46]:
group_year.get_group((2013,))

,date,meantemp,humidity,wind_speed,meanpressure,day,year,month,month_name
0,2013-01-01,10.000000,84.500000,0.000000,1015.666667,Tuesday,2013,1,January
1,2013-01-02,7.400000,92.000000,2.980000,1017.800000,Wednesday,2013,1,January
2,2013-01-03,7.166667,87.000000,4.633333,1018.666667,Thursday,2013,1,January
3,2013-01-04,8.666667,71.333333,1.233333,1017.166667,Friday,2013,1,January
4,2013-01-05,6.000000,86.833333,3.700000,1016.500000,Saturday,2013,1,January
...,...,...,...,...,...,...,...,...,...
360,2013-12-27,11.875000,79.875000,1.162500,1018.625000,Friday,2013,12,December
361,2013-12-28,10.875000,70.000000,5.325000,1019.250000,Saturday,2013,12,December
362,2013-12-29,10.571429,69.428571,5.325000,1018.500000,Sunday,2013,12,December
363,2013-12-30,12.375000,79.500000,6.475000,1018.125000,Monday,2013,12,December
364,2013-12-31,14.500000,89.375000,4.862500,1020.500000,Tuesday,2013,12,December

In [48]:
year=df['year'].unique()

In [49]:
year

array([2013, 2014, 2015, 2016, 2017], dtype=int32)

In [52]:
for y in year:
    data=group_year.get_group((y,))
    print("Year : ",y,"  ","Max MeanTemp : ",data['meantemp'].max())

Year :  2013    Max MeanTemp :  38.71428571428572
Year :  2014    Max MeanTemp :  38.5
Year :  2015    Max MeanTemp :  37.75
Year :  2016    Max MeanTemp :  38.27272727272727
Year :  2017    Max MeanTemp :  10.0

In [57]:
for y in year:
    data=group_year.get_group((y,))
    print("Year : ",y,"  ","Max humidity : ",data['humidity'].max())

Year :  2013    Max humidity :  94.0
Year :  2014    Max humidity :  96.85714285714286
Year :  2015    Max humidity :  98.0
Year :  2016    Max humidity :  94.3
Year :  2017    Max humidity :  100.0

In [56]:
for y in year:
    data=group_year.get_group((y,))
    print("Year : ",y,"  ","Max wind_speed : ",data['wind_speed'].max())

Year :  2013    Max wind_speed :  42.22
Year :  2014    Max wind_speed :  30.685714285714283
Year :  2015    Max wind_speed :  33.325
Year :  2016    Max wind_speed :  22.1
Year :  2017    Max wind_speed :  0.0

In [55]:

for y in year:
    data=group_year.get_group((y,))
    print("Year : ",y,"  ","Max meanpressure : ",data['meanpressure'].max())

Year :  2013    Max meanpressure :  1021.8
Year :  2014    Max meanpressure :  1023.0
Year :  2015    Max meanpressure :  1022.0
Year :  2016    Max meanpressure :  7679.333333333333
Year :  2017    Max meanpressure :  1016.0