In [1]:
import pandas as pd

In [2]:
data={
    "student":["Amit","Ram","Shyam","Bablu","Jacob"],
    "marks":[100,90,80,70,60],
    "rank":[1,2,3,4,5]
}

In [3]:
df=pd.DataFrame(data=data,index=[1,2,3,4,5])

In [4]:
df

  student  marks  rank
1    Amit    100     1
2     Ram     90     2
3   Shyam     80     3
4   Bablu     70     4
5   Jacob     60     5

In [5]:
df.iloc[[1,2]]

  student  marks  rank
2     Ram     90     2
3   Shyam     80     3

In [6]:
df.iloc[[1,2],[0,1]]

  student  marks
2     Ram     90
3   Shyam     80

In [7]:
for col in df:
    print(col)

student
marks
rank

In [8]:
df.dtypes

student    object
marks       int64
rank        int64
dtype: object

In [9]:
df.ndim

2

In [10]:
df.size

15

In [11]:
df.shape

(5, 3)

In [12]:
df.index

Index([1, 2, 3, 4, 5], dtype='int64')

In [13]:
df.T

            1    2      3      4      5
student  Amit  Ram  Shyam  Bablu  Jacob
marks     100   90     80     70     60
rank        1    2      3      4      5

In [14]:
df.head(2)

  student  marks  rank
1    Amit    100     1
2     Ram     90     2

In [15]:
df.tail(3)

  student  marks  rank
3   Shyam     80     3
4   Bablu     70     4
5   Jacob     60     5

In [16]:
data1={
    "student":["Amit","Ram","Shyam","Bablu","Jacob"],
    "marks":[100,90,80,70,60],
}

In [17]:
data2={
    "rank":[1,2,3,4,5],
    "address":["sangli","pune","satara",'kolhapur',"ashta"]
}

In [18]:
df1=pd.DataFrame(data1)

In [19]:
df2=pd.DataFrame(data2)

In [20]:
resdf=df1.join(df2)

In [21]:
resdf

  student  marks  rank   address
0    Amit    100     1    sangli
1     Ram     90     2      pune
2   Shyam     80     3    satara
3   Bablu     70     4  kolhapur
4   Jacob     60     5     ashta

In [22]:
data1={
    "student":["Amit","Ram","Shyam","Bablu","Jacob"],
    "marks":[100,90,80,70,60],
    "rank":[1,2,3,4,5]
}

In [23]:
data2={
    "student":["Amit","Ram","Shyam","Bablu","Jacob"],
    "marks":[100,90,80,70,60],
    "rank":[1,2,3,4,5]
}

In [24]:
df1=pd.DataFrame(data1)

In [25]:
df2=pd.DataFrame(data2)

In [26]:
resdf=pd.concat((df1,df2),ignore_index=True)

In [27]:
resdf

  student  marks  rank
0    Amit    100     1
1     Ram     90     2
2   Shyam     80     3
3   Bablu     70     4
4   Jacob     60     5
5    Amit    100     1
6     Ram     90     2
7   Shyam     80     3
8   Bablu     70     4
9   Jacob     60     5

In [28]:
data=[10,20,30,40,50,60,70,80,80,100]

In [29]:
s=pd.Series(data)

In [30]:
s

0     10
1     20
2     30
3     40
4     50
5     60
6     70
7     80
8     80
9    100
dtype: int64

In [31]:
s[5]

np.int64(60)

In [32]:
s.dtypes

dtype('int64')

In [33]:
s.ndim

1

In [34]:
s.size

10

In [35]:
s.shape

(10,)

In [36]:
s.name

In [37]:
s.hasnans

False

In [38]:
s.index

RangeIndex(start=0, stop=10, step=1)

In [39]:
s.head(4)

0    10
1    20
2    30
3    40
dtype: int64

In [40]:
s.tail()

5     60
6     70
7     80
8     80
9    100
dtype: int64

In [41]:
s.info()

<class 'pandas.core.series.Series'>
RangeIndex: 10 entries, 0 to 9
Series name: None
Non-Null Count  Dtype
--------------  -----
10 non-null     int64
dtypes: int64(1)
memory usage: 212.0 bytes

In [42]:
data1=[10,20,30,40,50]

In [43]:
s1=pd.Series(data1)

In [44]:
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [45]:
data2=[60,70,80,90,100]

In [46]:
s2=pd.Series(data2)

In [47]:
s2

0     60
1     70
2     80
3     90
4    100
dtype: int64

In [48]:
def bigger(x,y):
    if(x>y):
        return x
    else:
        return y
ress=s1.combine(s2,bigger)

In [49]:
ress

0     60
1     70
2     80
3     90
4    100
dtype: int64

In [50]:
s=pd.Series(data=['A','B','C','D','E','F'],dtype="category")

In [51]:
s

0    A
1    B
2    C
3    D
4    E
5    F
dtype: category
Categories (6, object): ['A', 'B', 'C', 'D', 'E', 'F']

In [52]:
df=pd.DataFrame(data=['A','B','C','D','E','F'],dtype='category')

In [53]:
df

   0
0  A
1  B
2  C
3  D
4  E
5  F

In [54]:
s

0    A
1    B
2    C
3    D
4    E
5    F
dtype: category
Categories (6, object): ['A', 'B', 'C', 'D', 'E', 'F']

In [55]:
s=s.cat.add_categories('G')

In [56]:
s

0    A
1    B
2    C
3    D
4    E
5    F
dtype: category
Categories (7, object): ['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [57]:
s=s.cat.remove_categories('G')

In [58]:
s

0    A
1    B
2    C
3    D
4    E
5    F
dtype: category
Categories (6, object): ['A', 'B', 'C', 'D', 'E', 'F']

In [59]:
df=pd.read_excel("Student.xlsx",index_col='Name')

In [60]:
df

       Marks  Rank
Name
Ram      100     1
Raj       90     2
Shyam     80     3
Pintu     70     4

In [61]:
df.loc["Ram",'Rank']

np.int64(1)

In [62]:
df["Marks"]

Name
Ram      100
Raj       90
Shyam     80
Pintu     70
Name: Marks, dtype: int64

In [63]:
df.reset_index()

    Name  Marks  Rank
0    Ram    100     1
1    Raj     90     2
2  Shyam     80     3
3  Pintu     70     4

In [64]:
df.iloc[0,1]

np.int64(1)

In [65]:
df.insert(2,"roll",[101,102,103,104])

In [66]:
df

       Marks  Rank  roll
Name
Ram      100     1   101
Raj       90     2   102
Shyam     80     3   103
Pintu     70     4   104

In [67]:
df.reset_index(inplace=True)

In [68]:
df

    Name  Marks  Rank  roll
0    Ram    100     1   101
1    Raj     90     2   102
2  Shyam     80     3   103
3  Pintu     70     4   104

In [69]:
df=df.assign(address=["sangli",'ashta','vadgoa','pune'])

In [70]:
df

    Name  Marks  Rank  roll address
0    Ram    100     1   101  sangli
1    Raj     90     2   102   ashta
2  Shyam     80     3   103  vadgoa
3  Pintu     70     4   104    pune

In [71]:
df.drop('roll',axis='columns',inplace=True)

In [72]:
df

    Name  Marks  Rank address
0    Ram    100     1  sangli
1    Raj     90     2   ashta
2  Shyam     80     3  vadgoa
3  Pintu     70     4    pune

In [73]:
df.drop(3,axis='index',inplace=True)

In [74]:
df

    Name  Marks  Rank address
0    Ram    100     1  sangli
1    Raj     90     2   ashta
2  Shyam     80     3  vadgoa

In [75]:
df.to_csv("clean.csv",index=False)

In [76]:
df=pd.read_csv("clean.csv")

In [77]:
df

    Name  Marks  Rank address
0    Ram    100     1  sangli
1    Raj     90     2   ashta
2  Shyam     80     3  vadgoa

In [78]:
for row in df.iterrows():
    print(row)
    print()

(0, Name          Ram
Marks         100
Rank            1
address    sangli
Name: 0, dtype: object)

(1, Name         Raj
Marks         90
Rank           2
address    ashta
Name: 1, dtype: object)

(2, Name        Shyam
Marks          80
Rank            3
address    vadgoa
Name: 2, dtype: object)

In [79]:
for row in df.itertuples():
    print(row)

Pandas(Index=0, Name='Ram', Marks=100, Rank=1, address='sangli')
Pandas(Index=1, Name='Raj', Marks=90, Rank=2, address='ashta')
Pandas(Index=2, Name='Shyam', Marks=80, Rank=3, address='vadgoa')

In [80]:
data={
    'student':["Amit","John","Jacob","David","Sleve"],
    'rank':[1,4,3,5,2],
    'marks':[95,70,80,60,90]
}

In [81]:
df=pd.DataFrame(data)

In [82]:
df

  student  rank  marks
0    Amit     1     95
1    John     4     70
2   Jacob     3     80
3   David     5     60
4   Sleve     2     90

In [83]:
res=df.sort_values(by='rank')

In [84]:
res

  student  rank  marks
0    Amit     1     95
4   Sleve     2     90
2   Jacob     3     80
1    John     4     70
3   David     5     60

In [85]:
res=df.sort_values(by='rank',ascending=False)

In [86]:
res

  student  rank  marks
3   David     5     60
1    John     4     70
2   Jacob     3     80
4   Sleve     2     90
0    Amit     1     95

In [87]:
data={
    'student':["Amit","John","Jacob","David","Sleve","Amit","Jacob"],
    'rank':[1,4,3,5,2,1,3],
    'marks':[95,70,80,60,90,95,80]
}

In [88]:
df=pd.DataFrame(data)

In [89]:
df

  student  rank  marks
0    Amit     1     95
1    John     4     70
2   Jacob     3     80
3   David     5     60
4   Sleve     2     90
5    Amit     1     95
6   Jacob     3     80

In [90]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
6     True
dtype: bool

In [91]:
res=df.drop_duplicates()

In [92]:
res

  student  rank  marks
0    Amit     1     95
1    John     4     70
2   Jacob     3     80
3   David     5     60
4   Sleve     2     90

In [93]:
import numpy as np

In [94]:
data={
    'student':["Amit","John","Jacob",np.nan,"Sleve","Amit",np.nan],
    'rank':[1,4,3,np.nan,2,1,3],
    'marks':[95,70,80,60,np.nan,95,80]
}

In [95]:
df=pd.DataFrame(data)

In [96]:
df

  student  rank  marks
0    Amit   1.0   95.0
1    John   4.0   70.0
2   Jacob   3.0   80.0
3     NaN   NaN   60.0
4   Sleve   2.0    NaN
5    Amit   1.0   95.0
6     NaN   3.0   80.0

In [97]:
resdf=df.isnull()

In [98]:
resdf

   student   rank  marks
0    False  False  False
1    False  False  False
2    False  False  False
3     True   True  False
4    False  False   True
5    False  False  False
6     True  False  False

In [99]:
resdf.count()

student    7
rank       7
marks      7
dtype: int64

In [100]:
resdf=df.notnull()

In [101]:
resdf

   student   rank  marks
0     True   True   True
1     True   True   True
2     True   True   True
3    False  False   True
4     True   True  False
5     True   True   True
6    False   True   True

In [102]:
df

  student  rank  marks
0    Amit   1.0   95.0
1    John   4.0   70.0
2   Jacob   3.0   80.0
3     NaN   NaN   60.0
4   Sleve   2.0    NaN
5    Amit   1.0   95.0
6     NaN   3.0   80.0

In [103]:
resdf=df.dropna(ignore_index=True)

In [104]:
resdf

  student  rank  marks
0    Amit   1.0   95.0
1    John   4.0   70.0
2   Jacob   3.0   80.0
3    Amit   1.0   95.0

In [105]:
df

  student  rank  marks
0    Amit   1.0   95.0
1    John   4.0   70.0
2   Jacob   3.0   80.0
3     NaN   NaN   60.0
4   Sleve   2.0    NaN
5    Amit   1.0   95.0
6     NaN   3.0   80.0

In [106]:
df['student']=df['student'].fillna("Tom")

In [107]:
df

  student  rank  marks
0    Amit   1.0   95.0
1    John   4.0   70.0
2   Jacob   3.0   80.0
3     Tom   NaN   60.0
4   Sleve   2.0    NaN
5    Amit   1.0   95.0
6     Tom   3.0   80.0

In [108]:
df['rank']=df['rank'].fillna(df['rank'].mean())

In [109]:
df

  student      rank  marks
0    Amit  1.000000   95.0
1    John  4.000000   70.0
2   Jacob  3.000000   80.0
3     Tom  2.333333   60.0
4   Sleve  2.000000    NaN
5    Amit  1.000000   95.0
6     Tom  3.000000   80.0

In [110]:
df['marks']=df['marks'].fillna(df['marks'].mean())

In [111]:
df

  student      rank  marks
0    Amit  1.000000   95.0
1    John  4.000000   70.0
2   Jacob  3.000000   80.0
3     Tom  2.333333   60.0
4   Sleve  2.000000   80.0
5    Amit  1.000000   95.0
6     Tom  3.000000   80.0

In [112]:
df

  student      rank  marks
0    Amit  1.000000   95.0
1    John  4.000000   70.0
2   Jacob  3.000000   80.0
3     Tom  2.333333   60.0
4   Sleve  2.000000   80.0
5    Amit  1.000000   95.0
6     Tom  3.000000   80.0

In [113]:
df['student']=df['student'].str.lower()

In [114]:
df

  student      rank  marks
0    amit  1.000000   95.0
1    john  4.000000   70.0
2   jacob  3.000000   80.0
3     tom  2.333333   60.0
4   sleve  2.000000   80.0
5    amit  1.000000   95.0
6     tom  3.000000   80.0

In [115]:
df['student']=df['student'].str.upper()

In [116]:
df

  student      rank  marks
0    AMIT  1.000000   95.0
1    JOHN  4.000000   70.0
2   JACOB  3.000000   80.0
3     TOM  2.333333   60.0
4   SLEVE  2.000000   80.0
5    AMIT  1.000000   95.0
6     TOM  3.000000   80.0

In [117]:
df['student']=df['student'].str.title()

In [118]:
df

  student      rank  marks
0    Amit  1.000000   95.0
1    John  4.000000   70.0
2   Jacob  3.000000   80.0
3     Tom  2.333333   60.0
4   Sleve  2.000000   80.0
5    Amit  1.000000   95.0
6     Tom  3.000000   80.0

In [119]:
df['student']=df['student'].str.len()

In [120]:
df

   student      rank  marks
0        4  1.000000   95.0
1        4  4.000000   70.0
2        5  3.000000   80.0
3        3  2.333333   60.0
4        5  2.000000   80.0
5        4  1.000000   95.0
6        3  3.000000   80.0

In [121]:
df['student'].count()

np.int64(7)

In [122]:
resdf.str.contains('Amit')

AttributeError: 'DataFrame' object has no attribute 'str'

In [123]:
resdf

  student  rank  marks
0    Amit   1.0   95.0
1    John   4.0   70.0
2   Jacob   3.0   80.0
3    Amit   1.0   95.0

In [125]:
pd.Timestamp.now()

Timestamp('2026-03-28 13:01:53.818121')

In [126]:
ts=pd.Timestamp(year=2024 , month=11,day=10)

In [127]:
ts

Timestamp('2024-11-10 00:00:00')

In [129]:
ts.dayofweek

6

In [130]:
ts.dayofyear

315

In [131]:
ts.daysinmonth

30

In [133]:
ts.is_leap_year

True

In [135]:
ts.is_month_end

False

In [136]:
ts.is_month_start

False

In [137]:
ts.is_year_end

False

In [138]:
ts.is_year_start

False

In [139]:
data=["\n\traju\n","\n\tram\n","\n\tShyam\t\n","\n\tRutwik\n"]

In [140]:
s=pd.Series(data)

In [141]:
s

0       \n\traju\n
1        \n\tram\n
2    \n\tShyam\t\n
3     \n\tRutwik\n
dtype: object

In [143]:
s.str.strip()

0      raju
1       ram
2     Shyam
3    Rutwik
dtype: object

In [144]:
s.str.lstrip()

0       raju\n
1        ram\n
2    Shyam\t\n
3     Rutwik\n
dtype: object

In [145]:
s.str.rstrip()

0      \n\traju
1       \n\tram
2     \n\tShyam
3    \n\tRutwik
dtype: object